# Generated by Django 4.1.4 on 2022-12-14 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mytodo',
            new_name='Todo',
        ),
    ]
